### PR TITLE
DBC->DBF file converter

### PR DESCRIPTION
**Pull request by ialek36**
Alberto,
I added DBC->DBF converter that writes DBF to file system.  This allows the framework to handle large resulting DBF files.  Let me know if you are interested.  Feel free to make any changes or offer any suggestions/corrections.

### CODE REVIEW

**Comment by albfernandez** [comment]
Thanks for the pull request

I'll review and merge it next week

**Comment by ialek36** [comment]
Awesome.  Thank you for approving!

**Comment by albfernandez** [comment]
After merging, I've changed some FileStreams to be Input/Output streams to be more generics.

And I've removed an unused DBFWriter constructor (tell me if you need it back)

**Comment by ialek36** [comment]
Thank you for the cleanup.  I think the DBFWriter constructor was a leftover that I ended up not using it.  I like the Input/Output stream changes.  It sets up nicely a path to adding support for HDFS.  Is it something you are interested in having in the framework?  I can try to see what it takes to add that.

**Comment by albfernandez** [comment]
HDFS = Apache Hadoop?
If so it's out of scope of the project (maybe creating a separate one). 
All help is always welcome.

**Comment by ialek36** [comment]
Yeah, I was thinking the same.  HDFS will pull a bunch of other dependencies that are not needed for the rest of the framework.  A separate project indeed sounds like a better approach.  This new project will have multiple parent/child structure.  The parent project will pull in javadbf and the child subprojects will have implementations for HDFS/S3/Azure/Google Cloud, etc; each with their own set of corresponding dependencies.

**Pull request merged**
